#include "bumpers.h"

#define LEFT_BUMPER_PIN PORT_PA04
#define RIGHT_BUMPER_PIN PORT_PA05
#define FRONT_BUMPER_PIN PORT_PA06
#define BACK_BUMPER_PIN PORT_PA07


void init_bumpers() {
	PORT->Group[0].DIRCLR.reg = LEFT_BUMPER_PIN | RIGHT_BUMPER_PIN | FRONT_BUMPER_PIN | BACK_BUMPER_PIN;
	PORT->Group[0].PINCFG[4] |= PORT_PINCFG_PULLEN;
	PORT->Group[0].PINCFG[5] |= PORT_PINCFG_PULLEN;
	PORT->Group[0].PINCFG[6] |= PORT_PINCFG_PULLEN;
	PORT->Group[0].PINCFG[7] |= PORT_PINCFG_PULLEN;
	PORT->Group[0].OUTSET.reg =  LEFT_BUMPER_PIN | RIGHT_BUMPER_PIN | FRONT_BUMPER_PIN | BACK_BUMPER_PIN;
}
int bumpers_is_pushed() {
	return (~PORT->Group[0].IN.reg &(LEFT_BUMPER_PIN | RIGHT_BUMPER_PIN | FRONT_BUMPER_PIN | BACK_BUMPER_PIN))!=0;
}
